### Get home route
GET http://{{ host }}:{{ port }}
Accept: application/json

### Create a post
POST http://{{ host }}:{{ port }}/posts
Accept: application/json
Content-Type: application/json

{
    "title": "A second Lorem Ipsum post",
    "body": "Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna."
}

### Invalid title (too long)
POST http://{{ host }}:{{ port }}/posts
Accept: application/json
Content-Type: application/json

{
    "title": "A second Lorem Ipsum post with too many characters in the title",
    "body": "Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna."
}

### Missing title
POST http://{{ host }}:{{ port }}/posts
Accept: application/json
Content-Type: application/json

{
    "body": "Sed enim mi, bibendum eu pulvinar vel, sodales vitae dui. Pellentesque sed sapien lorem, at lacinia urna."
}

### Missing body
POST http://{{ host }}:{{ port }}/posts
Accept: application/json
Content-Type: application/json

{
    "title": "I am missing a body"
}

### Publish post
PUT http://{{ host }}:{{ port }}/publish/5
Accept: application/json

###