home:
  path: /
  defaults: { _controller: BlogBundle:Home:home }
  methods: [GET]

create_post:
  path: /posts
  defaults: { _controller: BlogBundle:Post:createPost }
  methods: [POST]

publish_post:
  path: /publish/{postId}
  defaults: { _controller: BlogBundle:Post:publishPost }
  methods: [PUT]
  requirements:
    postId: '\d+'

find_posts:
  path: /posts
  defaults: { _controller: BlogBundle:Post:findPosts }
  methods: [GET]